[package]
name = "netcdf"
version = "0.1.0"
authors = ["Michael Hiley <mike.hiley@ssec.wisc.edu>"]
license = "MIT OR Apache-2.0"
description = "High-level NetCDF bindings for Rust"
repository = "https://github.com/mhiley/rust-netcdf"
documentation = "https://github.com/mhiley/rust-netcdf"
keywords = ["netcdf", "hdf", "hdf5", "libnetcdf", "netcdf4"]

[dependencies]
libc = "0.2"
lazy_static = "1.0"
ndarray = "0.11.0"

[dependencies.netcdf-sys]
path = "netcdf-sys"
